print("all")
print(all([1, 2]))
print(all([1, 2, 0]))
print(all([]))
print()
print("any")
print(any([1, 2]))
print(any([1, 2, 0]))
print(any([0, 0]))
print(any([]))
print("sorted")
a = {4: 103, 2: 11, 7: 88, 6: 99}

print(a)
print(sorted(a.items()))
print(sorted(a.items(), key=lambda x: x[1]))
