list1 = [1, 1, 2, 3]
tuple1 = (1, 1, 2, 3)
set1 = set(list1)
print(list1, type(list1))
print(tuple1, type(tuple1))
print(set1, type(set1))
set2 = {2, 3, 4, 4}
set3 = {2, 3}
print("交集：", set1.intersection(set2), set1 & set2)
print("并集：", set1.union(set2), set1 | set2)
print("差集：", set1.difference(set2), set1 - set2)
print("差集：", set2.difference(set1), set2 - set1)
print("子集：", set1.issubset(set2))
print("子集：", set2.issubset(set1))
print("子集：", set3.issubset(set1))
print("超集：", set3.issuperset(set1))
print("超集：", set1.issuperset(set3))
print("超集：", set1.issuperset(set2))
print("对称差集：", set1.symmetric_difference(set2), set1 ^ set2)
print("不相交集：", set1.isdisjoint(set2))
print(len(list1))
print(len(tuple1))
print(len(set1))

print(4 in list1)
print(1 in tuple1)
print(4 in set1)
print("e" in "abcd")
dic = {"name1": "lily", "name2": "lucy"}
print("lily" in dic)
set1.add(33)
set1.add(333)
set1.add(343)
print(set1)
set1.pop()
print(set1)
set1.remove(333)
set1.discard(22)
print(set1)
