import hashlib

print("md5")
m = hashlib.md5()
m.update(b"hello")
print(m.digest())
print(m.hexdigest())
m.update(b"i am tom")  # 多次update是将字符串拼接起来
print(m.hexdigest())
m2 = hashlib.md5()
m2.update(b"helloi am tom")
print(m2.hexdigest())
m3 = hashlib.md5()
m3.update("helloi am tom 上帝发誓地方".encode())
print(m3.hexdigest())
print()
print("sha1")
s1 = hashlib.sha1()
s1.update(b"helloi am tom")
print(s1.hexdigest())
print()
print("sha256")
s2 = hashlib.sha256()
s2.update(b"helloi am tom")
print(s2.hexdigest())
