import os

print(os.getcwd())
# os.chdir(r"../04")
# print(os.getcwd())
print(os.curdir)
print(os.pardir)
# os.makedirs(r"C:\soft\PyCharmProjects\day01\05\01\02")
# os.removedirs(r"C:\soft\PyCharmProjects\day01\05\01\02")
# os.mkdir(r"C:\soft\PyCharmProjects\day01\05\01")
# os.rmdir(r"C:\soft\PyCharmProjects\day01\05\01")
print(os.listdir(".."))
print(os.name)
print(os.sep)
print(os.linesep)
print(os.pathsep)
print(os.environ)
print(os.path.abspath("."))
print(os.path.basename(r"C:\soft\PyCharmProjects\day01\05"))
print(os.path.basename(r"C:\soft\PyCharmProjects\day01\05\moduleFun.py"))
print(os.path.exists(r"C:\soft\PyCharmProjects\day01\05\moduleFun.py"))
print(os.path.isfile(r"C:\soft\PyCharmProjects\day01\05\moduleFun.py"))
print(os.path.isdir("C:\soft\PyCharmProjects\day01\05\moduleFun.py"))
print(os.path.dirname(os.path.abspath(".")))
# os.system("notepad")